### ISSUE TITLE
Subscribe button has 'hidden' attribute for some reason

### ISSUE THREAD

**Issue by TorutheRedFox** [omnidevZero/YouTubeRedux#132]
lemme guess, YouTube being YouTube again

fix:
```CSS
.ytd-subscribe-button-renderer[hidden] {
  display: flex;
}
```
