### ISSUE TITLE
Extra scrollbar in Firefox?

### ISSUE THREAD

**Issue by Amariithynar** [omnidevZero/YouTubeRedux#139]
Firefox version 109, not sure what options are causing it, but there's an extra scrollbar internally, beside the actual page scrollbar.
![image](https://user-images.githubusercontent.com/22435375/215620591-aff71656-cd28-4dff-993c-bb4600d29622.png) these are my settings, and 
![image](https://user-images.githubusercontent.com/22435375/215620782-297ff983-387f-44a1-9ac6-895a95943500.png)
this is the doubled scrollbar. It even appears when in fullscreen mode.

**Comment by TorutheRedFox** [comment]
i did some css modding to reform the way the page is laid out so it doesn't use flex anymore and that as a side effect made it go away

**Comment by Amariithynar** [comment]
I know nothing about CSS; can you either walk me through it, or provide something I can put somewhere to resolve it?

**Comment by Thespikedballofdoom** [comment]
ytd-page-manager {
  overflow-y: hidden;
}
https://addons.mozilla.org/en-US/firefox/addon/styl-us/

**Comment by Amariithynar** [comment]
> ytd-page-manager { overflow-y: hidden; } https://addons.mozilla.org/en-US/firefox/addon/styl-us/

This worked perfectly, thank you so much!

**Comment by TorutheRedFox** [comment]
for those who want it:

my CSS (for use in Stylebot)

```CSS
/* player button size css patches */

.ytp-chrome-controls .ytp-button[aria-pressed=true]:after {
    width: 20px;
    left: 8px;
}

.ytp-chrome-controls .ytp-button[aria-pressed]:after {
  bottom: 5px;
}

.ytp-big-mode .ytp-chrome-bottom {
    height: 54px;
    padding-top: 4px;
}

.ytp-big-mode .ytp-progress-bar-container {
    bottom: 52.5px;
    height: 8px;
}

.ytp-big-mode .ytp-chrome-controls {
    height: 54px;
    line-height: 54px;
}

.ytp-big-mode .ytp-time-display {
    line-height: 53px;
}

.ytp-big-mode .ytp-chrome-top .ytp-button, .ytp-big-mode .ytp-chrome-controls .ytp-button {
    width: 54px;
}

.ytp-big-mode .ytp-chrome-controls .ytp-play-button {
    width: 69px;
}

.ytp-chrome-bottom {
    height: 36px;
}

.ytp-progress-bar-container {
    bottom: 35px;
    height: 5px;
}

.ytp-chrome-controls {
    height: 36px;
    line-height: 36px;
}

.ytp-small-mode .ytp-time-display, .ytp-time-display {
    line-height: 36px;
}

.ytp-chrome-top .ytp-button, .ytp-chrome-controls .ytp-button, .ytp-replay-button {
    opacity: .9;
    width: 36px;
    padding: 0px;
}

.ytp-chrome-controls .ytp-button.ytp-mute-button {
  padding: 3.1px;
}

.ytp-chrome-controls .ytp-play-button {
    width: 46px;
}

.ytp-chrome-controls .ytp-button {
    height: 100%;
}

.ytp-chapter-title.ytp-button, .ytp-big-mode .ytp-chapter-title.ytp-button, .ytp-small-mode .ytp-chrome-controls .ytp-chapter-title.ytp-button, .ytp-embed-mobile-exp .ytp-chrome-controls .ytp-chapter-title.ytp-button {
    width: 100%;
    display: -webkit-box;
    display: -webkit-flex;
    display: -moz-box;
    display: -ms-flexbox;
    display: flex;
    -webkit-box-align: center;
    -webkit-align-items: center;
    -moz-box-align: center;
    -ms-flex-align: center;
    align-items: center;
}

.ytp-chrome-top .ytp-cards-button {
  margin-top: 7px;
}

/* youtube redux css patches */

ytd-expander#expander {
  overflow: hidden;
}

span.ytd-video-owner-renderer {
  line-height: 24px; 
  height: 22px;
  padding: 0 6px;
  font-size: 11px;
  text-align: center;
}

yt-formatted-string.style-scope.ytd-channel-name::before {
  content: "by ";
}

.style-scope.ytd-search .style-scope.ytd-channel-name::before {
    color: var(--yt-endpoint-color,var(--yt-spec-text-primary));
}

.ytd-video-secondary-info-renderer yt-formatted-string.style-scope.ytd-channel-name::before, .channel-link yt-formatted-string.style-scope.ytd-channel-name::before, .ytd-author-comment-badge-renderer yt-formatted-string.style-scope.ytd-channel-name::before, .ytd-c4-tabbed-header-renderer yt-formatted-string.style-scope.ytd-channel-name::before {
  content: "";
}

#container.ytd-masthead {
    height: 49px;
}

ytd-watch-flexy:not([theater]):not([fullscreen]) #primary.ytd-watch-flexy, ytd-watch-flexy:not([theater]):not([fullscreen]) #secondary.ytd-watch-flexy {
    padding-top: 4px !important;
}

#guide-spacer.ytd-app {
    margin-top: 50px;
}

ytd-feed-filter-chip-bar-renderer {
    margin-left: 0px;
}

#chips-wrapper.ytd-feed-filter-chip-bar-renderer {
    width: var(--ytd-rich-grid-chips-bar-width);
}



ytd-menu-renderer ytd-menu-renderer .ytd-menu-renderer[style-target=button], .ytd-menu-renderer[style-target=button], ytd-button-renderer[is-icon-button][style-action-button],
ytd-download-button-renderer  {
    vertical-align: top;
}

ytd-download-button-renderer {
  padding-left: 6px;
}

ytd-video-primary-info-renderer:after {
    --yt-icon-button-icon-width: 24px;
    --yt-icon-button-icon-height: 24px;
    width: var(--yt-icon-width);
    height: 32px;
    content: "";

    display: inline-block;
    box-sizing: border-box;
    font-size: 0;
}

#button.dropdown-trigger {
  height: 36px;
}

yt-formatted-string.style-scope.ytd-toggle-button-renderer.style-text, yt-formatted-string.style-scope.ytd-toggle-button-renderer.style-default-active {
  font-weight: 500;
  font-size: 11px;
  text-decoration: none;
  white-space: nowrap;
  word-wrap: normal;
  line-height: normal;
  vertical-align: middle;
}

ytd-video-primary-info-renderer {
    padding: 15px;
    padding-bottom: 5px;
    position: relative;
}

#info.ytd-watch-flexy {
  min-height: 150px;
}

.redux-moved-info:last-of-type + yt-icon-button {
    transform: translateY(-2px);
}
yt-formatted-string.style-scope.ytd-subscribe-button-renderer {
  font-weight: normal;
  font-size: 100%;
}

/* small thumbnails */
ytd-compact-video-renderer:not([watch-feed-big-thumbs]) ytd-thumbnail.ytd-compact-video-renderer, ytd-compact-radio-renderer:not([watch-feed-big-thumbs]) ytd-thumbnail.ytd-compact-radio-renderer, ytd-compact-playlist-renderer:not([watch-feed-big-thumbs]) ytd-playlist-thumbnail.ytd-compact-playlist-renderer, ytd-compact-movie-renderer:not([watch-feed-big-thumbs]) ytd-thumbnail.ytd-compact-movie-renderer {
    height: 67px;
    width: 120px;
}

ytd-playlist-renderer[is-search] ytd-playlist-thumbnail.ytd-playlist-renderer, 
#avatar-section.ytd-channel-renderer {
    max-width: 246px;
}

ytd-channel-renderer #avatar-section.ytd-channel-renderer .channel-link.ytd-channel-renderer {
    justify-content: center !important;
}

ytd-button-renderer.ytd-item-section-renderer, ytd-compact-radio-renderer.ytd-item-section-renderer, ytd-compact-video-renderer.ytd-item-section-renderer, ytd-compact-movie-renderer.ytd-item-section-renderer, ytd-compact-playlist-renderer.ytd-item-section-renderer, ytd-emergency-onebox-renderer.ytd-item-section-renderer, ytd-feed-nudge-renderer.ytd-item-section-renderer, ytd-movie-renderer.ytd-item-section-renderer, ytd-playlist-renderer.ytd-item-section-renderer, ytd-show-renderer.ytd-item-section-renderer, ytd-radio-renderer.ytd-item-section-renderer, yt-search-no-results-renderer.ytd-item-section-renderer, ytd-video-renderer.ytd-item-section-renderer, ytd-channel-renderer.ytd-item-section-renderer, ytd-promoted-sparkles-text-search-renderer.ytd-item-section-renderer, ytd-web-answer-renderer.ytd-item-section-renderer, ytd-clarification-renderer.ytd-item-section-renderer, ytd-fact-check-renderer.ytd-item-section-renderer, ytd-info-panel-container-renderer.ytd-item-section-renderer {
    margin-top: 15px;
}

#secondary-inner.ytd-watch-flexy #related, #secondary-inner.ytd-watch-flexy #playlist + #related:not(#secondary-inner.ytd-watch-flexy #playlist[hidden="true"] + #related) {
  padding-top: 0px;
}

.ytd-compact-video-renderer .badge-style-type-simple, .ytd-compact-video-renderer .badge-style-type-live-now-alternate {
    margin-top: -18px;
    font-size: 11px;
    height: 10px;
    padding-top: 1px;
    position: absolute;
    left: 53%;
}

ytd-rich-item-renderer .badge-style-type-simple, .ytd-rich-item-renderer .badge-style-type-live-now-alternate {
    margin-top: -28px;
    position: absolute;
    right: 0;
    font-size: 11px;
    height: 14px;
    padding-top: 1px;
}

#meta.ytd-rich-grid-media {
    overflow-y: hidden;
}

.ytd-compact-video-renderer .badge-style-type-live-now-alternate {
  padding-top: 1px;
  padding-bottom: 4px;
}

div #show-more-related {
  padding-top: 11px;
  padding-bottom: 8px;
}

#related {
  margin-bottom: 32px;
}

#commentbox #creation-box, #placeholder-area.ytd-comment-simplebox-renderer {
    min-height: 32px;
}

#action-buttons.ytd-comment-renderer {
    margin-top: -2px;
}

#more-replies, #less-replies {
  margin-top: 2px;
  margin-bottom: 0px;
}


.ytd-comment-thread-renderer {
  margin-bottom: -16px;
  margin-top: 8px;
}

ytd-comments-header-renderer {
    margin-top: 12px;
    margin-bottom: 12px;
}

#title.ytd-comments-header-renderer {
    margin-bottom: 12px;
}

#meta.ytd-watch-flexy tp-yt-paper-button#more {
  margin-top: 0px;
}

ytd-video-secondary-info-renderer {
    padding-bottom: 4px !important;
}

#show-more-related {
  padding-bottom: 0px;
}

.style-scope.ytd-comment-replies-renderer #commentbox #creation-box::before {
  top: -4px;
} 

#count.ytd-comments-header-renderer yt-formatted-string span:last-child::after {
    content: '(';
    margin: 0 5px;
    margin-right: 0px;
    min-width: 160px;
}

ytd-video-view-count-rende

#count.ytd-comments-header-renderer yt-formatted-string span:last-child::before {
    content: ' All';
    margin: 0 0;
}

#count.ytd-comments-header-renderer yt-formatted-string span:first-child::after {
    content: ')';
}

.ytp-spinner {
  transform: scale(0.5) translateZ(0);
}

#logo.ytd-topbar-logo-renderer, ytd-yoodle-renderer.ytd-topbar-logo-renderer {
  margin-top: 0px;
}

#author-comment-badge.ytd-comment-renderer, #sponsor-comment-badge.ytd-comment-renderer, #header.ytd-comment-renderer {
  margin-top: -2px;
  margin-bottom: 0px;
}

#pinned-comment-badge.ytd-comment-renderer {
    margin-bottom: 0px;
}

.ytd-comment-renderer #text.ytd-channel-name {
    font-size: var(--ytd-channel-name-text-font-size);
}

.ytd-comment-renderer[creator] {
  background-color: #0465f1;
  color: #fff;
}

ytd-author-comment-badge-renderer[creator] {
  height: 16px;
  border-radius: 0px;
  margin-bottom: 0px;
  padding-right: 2px;
  padding-left: 2px;
}

#content-text.ytd-comment-renderer {
  font-size: 14px;
}

.bold.yt-formatted-string {
    font-weight: bold;
}

#content-text.ytd-comment-renderer {
    line-height: 16px !important;
}

#author-thumbnail.ytd-comment-renderer yt-img-shadow.ytd-comment-renderer {
    margin-right: 12px;
}

ytd-comment-replies-renderer.ytd-comment-thread-renderer {
  margin-left: 52px;
}

.ytd-comment-replies-renderer #button.ytd-button-renderer #text.ytd-button-renderer span:first-child::after {
  content: "all ";
}

.ytd-comment-replies-renderer #button.ytd-button-renderer #text.ytd-button-renderer span:first-child::after {
  content: "all ";
}

.ytd-comment-replies-renderer #button.ytd-button-renderer yt-icon.ytd-button-renderer+yt-formatted-string.ytd-button-renderer, #expander.ytd-comment-replies-renderer .expander-header.ytd-comment-replies-renderer[teaser] #more-replies.ytd-comment-replies-renderer {
  order: 0;
  margin-left: -4px;
  font-size: 14px;
}

#expander.ytd-comment-replies-renderer .expander-header.ytd-comment-replies-renderer[teaser] #more-replies.ytd-comment-replies-renderer {
  margin-left: 2px;
}

ytd-comment-replies-renderer:not([modern]) #expander .ytd-comment-replies-renderer .dot.ytd-comment-replies-renderer
{
  display: none;
}
.ytd-comment-replies-renderer ytd-button-renderer[is-paper-button] yt-icon.ytd-button-renderer, ytd-comment-replies-renderer:not([modern]) .more-button.ytd-comment-replies-renderer {
  order: 1;
  margin-left: 2px;
}

 ytd-comment-replies-renderer:not([modern]) .more-button.ytd-comment-replies-renderer {
  height: 20px;
  padding-bottom: 4px;
  margin-top: 4px;
 }

.ytd-comment-replies-renderer #button {
  --yt-button-padding: 0px 0 8px 0;
}

.ytd-comment-replies-renderer .ytd-comment-action-buttons-renderer #button {
  --yt-button-padding: 0px 0 0px 0;
}

/* set font family for everything */
* { 
  font-family: Arial, Helvetica, sans-serif;
}

#playlist {
  padding-left: 12px;
}

#upload-info.ytd-video-owner-renderer {
  margin-top: -4px;
}

#search-form.ytd-searchbox, #search-icon-legacy.ytd-searchbox {
  height: 29px;
}

#search-icon-legacy.ytd-searchbox yt-icon.ytd-searchbox {
  width: 18px;
  height: 18px;
  margin-top: -1px;
  margin-left: -2px;
}

#country-code.ytd-topbar-logo-renderer {
  margin-top: 17px;
}

#container.ytd-searchbox {
  margin-left: -10px;
}

ytd-searchbox.ytd-masthead {
  margin-right: 29px;
}

[dark] #search-icon-legacy.ytd-searchbox {
  border-color: #404040;
}

#search-icon-legacy.ytd-searchbox {
  border-color: #d3d3d3;
  border-left: 0;
  -moz-border-radius-topleft: 0;
  border-top-left-radius: 0;
  -moz-border-radius-bottomleft: 0;
  border-bottom-left-radius: 0;
  width: 66px;
}

#search-icon.ytd-searchbox {
  display: none;
  width: 0px;
}

ytd-searchbox[has-focus] #container.ytd-searchbox {
  margin-left: -10px !important;
  padding: 2px 6px;
}

ytd-video-renderer[is-search] ytd-thumbnail.ytd-video-renderer {
  height: 137px;
}

#primary.ytd-watch-flexy {
  padding-left: 0px;
  margin-left: 0px;
}

#primary.ytd-watch-flexy > #primary-inner {
  padding-left: 0px;
}

ytd-watch-flexy[flexy] #secondary.ytd-watch-flexy {
  padding-right: 0px;
  margin-right: 0px;
}

.title.ytd-video-primary-info-renderer, .title.style-scope.ytd-video-primary-info-renderer yt-formatted-string.ytd-video-primary-info-renderer {
  font-size: 20px;
  font-weight: normal;
  font-family: Arial, Helvetica, sans-serif;
  line-height: normal;
  word-wrap: break-word;
}

.redux-moved-info:last-of-type + yt-icon-button {
    transform: none;
}

body {
    word-wrap: break-word;
    margin: 0;
    padding: 0;
    font: 12px Arial, Helvetica, sans-serif;
}

#info.ytd-video-primary-info-renderer > #menu-container {
    transform: translateY(42px) !important;
    min-width: 160px;
}

#avatar.ytd-video-owner-renderer {
  margin-right: 12px;
}

.ytd-video-owner-renderer #text.ytd-channel-name {
    display: inline-block;
    height: 22px;
    color: #333;
    max-width: 315px;
    overflow: hidden;
    text-overflow: ellipsis;
    vertical-align: top;
    font-size: 13px;
    line-height: normal;
}

.ytd-video-owner-renderer.ytd-video-owner-renderer.ytd-video-owner-renderer.ytd-video-owner-renderer #text.ytd-channel-name.ytd-channel-name.ytd-channel-name.ytd-channel-name.ytd-channel-name:hover {
  text-decoration: underline;
  -webkit-text-decoration: underline;
}

.redux-moved-info:first-of-type yt-icon-button#button {
  margin-left: -8px;
  padding-left: 0px;
  padding-right: 0px;
}

ytd-watch-flexy[flexy][is-two-columns_] #columns.ytd-watch-flexy {
    max-width: 1066px;
    min-width: 1003px;
    width: auto;
    overflow: hidden;
}

@media screen and (min-width: 1294px) and (min-height: 630px) {
ytd-watch-flexy[flexy][is-two-columns_] #columns.ytd-watch-flexy {
    max-width: 1280px !important;
}
}

#items.ytd-watch-next-secondary-results-renderer {
  padding-right: 15px;
}

#primary.ytd-watch-flexy, #secondary.ytd-watch-flexy {
  margin-bottom: 10px;
}

ytd-watch-flexy:not([theater]):not([fullscreen]) #primary.ytd-watch-flexy, ytd-watch-flexy:not([theater]):not([fullscreen]) #secondary.ytd-watch-flexy {
    padding-top: 10px !important;
}

#reply-button-end {
  order:1;
}

#share-button {
  order:3;
}

#creator-heart {
  order:2;
  margin-left: -8px;
  margin-right: -8px;
}

#vote-count-middle.ytd-comment-action-buttons-renderer {
  margin-right: 8px;
}

#vote-count-left.ytd-comment-action-buttons-renderer[hidden]+#like-button.ytd-comment-action-buttons-renderer {
    margin-left: 8px;
}

#less-replies {
  margin-left: 4px;
  margin-top: 3px;
}

.badge-style-type-collection {
  display: none;
}

yt-formatted-string[is-empty]:not(.use-shadow) {
    display: unset !important;
}

/* fixes for new layout */ 
 ytd-segmented-like-dislike-button-renderer {
   float: right;
 }
 #menu-container {
   margin-bottom: 6px;
 }

 html[dark] ytd-masthead, html[dark]
#guide-content {
   background: #222222;
 }

 ytd-merch-shelf-renderer {
   display: none;
 }

.ytp-ce-video.ytp-ce-medium-round, .ytp-ce-playlist.ytp-ce-medium-round, .ytp-ce-medium-round .ytp-ce-expanding-overlay-background, .ytp-videowall-still-round-medium .ytp-videowall-still-image, .ytp-videowall-still-round-large .ytp-videowall-still-image, .ytp-ce-video.ytp-ce-large-round, .ytp-ce-playlist.ytp-ce-large-round, .ytp-ce-large-round .ytp-ce-expanding-overlay-background {
    border-radius: 0px;
}

.ytp-settings-menu.ytp-rounded-menu, .ytp-screen-mode-menu.ytp-rounded-menu, .ytp-sb-subscribe.ytp-sb-rounded, .ytp-sb-unsubscribe.ytp-sb-rounded {
  border-radius: 2px;
}

#reduxSubDiv {
    margin-top: -0px !important;
}

#avatar, #avatar > #img {
  width: 48px !important;
  height: 48px;
}

#top-row.ytd-video-secondary-info-renderer {
    margin-bottom: 6px;
    padding-top: 8px;
}

.ytd-video-owner-renderer ytd-badge-supported-renderer {
  padding-bottom: 8px;
}

span.ytd-video-view-count-renderer {
  font-weight: normal;
  font-size: 19px;
}

yt-formatted-string[is-empty]:not(.use-shadow){display: unset !important;}
 #related #metadata-line.ytd-video-meta-block span:nth-child(2) {display: unset !important;}
 #secondary-text {display: none !important;}
 #related #metadata-line.ytd-video-meta-block > .ytd-video-meta-block:not(:last-of-type)::after {display: unset !important;}

 #metadata-line.ytd-video-meta-block>.ytd-video-meta-block:not(:first-of-type) {
   display: none;
 }

tp-yt-paper-button.ytd-toggle-button-renderer  {
  padding: 0.7em 0.57em;
}

#segmented-dislike-button #text {
  margin-left: var(--yt-string-icon-padding,8px);
      font-weight: 500 !important;
    font-size: 11px !important;
    text-decoration: none !important;
    white-space: nowrap !important;
    word-wrap: normal !important;
    line-height: normal !important;
    vertical-align: middle !important;
    color: var(--yt-button-color,inherit);
    background-color: transparent;
    text-transform: var(--yt-button-text-transform,inherit);

}

#segmented-dislike-button button.yt-icon-button {
    width: var(--yt-paper-button-width,auto);
    height: var(--yt-paper-button-height,auto);
    border-radius: inherit;
    margin: 0 var(--yt-button-paper-button-margin-right,0) 0 var(--yt-button-paper-button-margin-left,0);
    padding: var(--yt-button-padding,0.7em 0.57em);
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: center;
    flex: 1 1 auto;
    padding-right: 0px;
    padding-left: 12px;
}

#segmented-dislike-button yt-icon-button {
  padding: 0;
  margin: 0;
  width: fit-content;
  display: flex;
}

#segmented-dislike-button {
  border-radius: 2px;
}

ytd-toggle-button-renderer[is-paper-button-with-icon] tp-yt-paper-button.ytd-toggle-button-renderer {
    min-width: 0px;
}

ytd-video-primary-info-renderer #top-level-buttons-computed > ytd-toggle-button-renderer:first-of-type > a > yt-icon-button > #button[aria-pressed="true"] > yt-icon, #segmented-like-button[aria-pressed="true"] yt-icon, #segmented-like-button > .ytd-segmented-like-dislike-button-renderer > a > #button[aria-pressed="true"] > yt-icon {
content: url(chrome-extension://mdgdgieddpndgjlmeblhjgljejejkikf/images/like-pressed.png) !important;
    filter: contrast(1);
}

.ytd-player {
  background-color: black;
}

#sponsor-button.ytd-video-owner-renderer:not(:empty), #purchase-button.ytd-video-owner-renderer:not(:empty), #analytics-button.ytd-video-owner-renderer:not(:empty) {
    margin-right: 0px;
    display: flex;
    flex-direction: column;
    justify-content: center;
}

ytd-browse, ytd-search, #page-manager ytd-browse[page-subtype="home"], #tabsContainer {
    max-width: 1066px !important;
    min-width: 1003px !important;
    width: auto !important;
    margin: auto;
}

ytd-page-manager {
  margin-left: 0px;
}

ytd-app[guide-persistent-and-visible] ytd-page-manager.ytd-app {
    margin-left: 230px;
}

ytd-browse ytd-c4-tabbed-header-renderer[has-channel-art] .banner-visible-area.ytd-c4-tabbed-header-renderer {
    height: 177px;
}

@media screen and (min-width: 1294px) and (min-height: 630px) {

ytd-browse, ytd-search, #page-manager ytd-browse[page-subtype="home"], #tabsContainer {
    max-width: 1280px !important;
}

ytd-c4-tabbed-header-renderer[has-channel-art] .banner-visible-area.ytd-c4-tabbed-header-renderer {
    height: 212px !important;
}

}

ytd-app {
    --app-drawer-width: 240px;
    --ytd-mini-guide-width: 72px;
    --app-drawer-content-container-background-color: var( --yt-spec-general-background );
    background: var(--yt-spec-general-background);
}

ytd-browse[page-subtype=channels] {
  background: var(--yt-spec-general-background);
}

[page-subtype="channels"] ytd-rich-grid-row > #contents {
    justify-content: start;
}

ytd-rich-grid-row[is-slim-grid] #contents.ytd-rich-grid-row {
    margin: 0 0 0 16px;
}
.ytd-two-column-search-results-renderer {
  width: 100%;
  max-width: 100%;
}

ytd-c4-tabbed-header-renderer:not([has-channel-art]) .banner-visible-area.ytd-c4-tabbed-header-renderer {
  height: calc((100vw - 240px) / 6.2 - 1px);
  background-color: #333;
  background-image: url("/yts/img/channels/c4/default_banner_hq-vfl4dpY8T.png");
}

#menu .ytd-video-primary-info-renderer {
  overflow: hidden;
}

.ytd-subscribe-button-renderer[hidden] {
  display: flex;
}

.ytd-video-owner-renderer #redux-trim-span {
  border-left: none;
}

#columns {
  display: block;
  position: relative;
}

#primary.ytd-watch-flexy {
  margin-left: 0;
  padding-left: 0;
}

#secondary.ytd-watch-flexy {
    margin-left: 650px !important;
    margin-bottom: 20px !important;
    -moz-transition: margin-top .3s ease-in-out,padding-top .3s ease-in-out;
    -webkit-transition: margin-top .3s ease-in-out,padding-top .3s ease-in-out;
    transition: margin-top .3s ease-in-out,padding-top .3s ease-in-out;
    position: relative !important;
    margin-right: 0;
  padding-right: 0;
  width: auto;
}

@media screen and (min-width: 1080px) and (min-height: 560px) {
#secondary.ytd-watch-flexy {
    margin-left: 650px !important;
}
}

#secondary-inner.ytd-watch-flexy #related #items ytd-item-section-renderer #contents > :first-child::after, #secondary > #secondary-inner > #related > ytd-watch-next-secondary-results-renderer > #items > ytd-compact-video-renderer:first-child::after, #secondary > #secondary-inner > #related > ytd-watch-next-secondary-results-renderer > #items > ytd-compact-radio-renderer:first-child::after, #secondary > #secondary-inner > #related > ytd-watch-next-secondary-results-renderer > #items > ytd-compact-playlist-renderer:first-child::after {
  width: 100%;
}

@media screen and (min-width: 1294px) and (min-height: 630px)  { 
#secondary.ytd-watch-flexy {
    margin-left: 864px !important;
}
}

@media screen and (min-width: 1080px) and (min-height: 560px) {
#primary.ytd-watch-flexy {
    width: 640px !important;
}
}

@media screen and (min-width: 1294px) and (min-height: 630px) {
#primary.ytd-watch-flexy {
    width: 854px !important;
}
}

#primary.ytd-watch-flexy {
    z-index: 0;
    float: left;
    clear: left;
    position: static !important;
}

#related.ytd-watch-flexy {
  margin-left: 0;
  margin-right: 0;
  padding-right: 0;
}

#playlist.ytd-watch-flexy > #container {
    margin-right: 0;
    width: auto;
    padding-left: 0;
    padding-right: 0;
    position: relative;
    transform: none;
      max-width: none;
}

#playlist.ytd-watch-flexy {
  transform: none;
  margin-left: 0px;
  padding-left: 0px;
  width: auto;
  max-width: none;
}

#player.ytd-watch-flexy {
    margin-bottom: 7px;
}

#below.ytd-watch-flexy {
  margin-top: -3px;
  padding-top: 0px;
}

div #show-more-related {
  margin-right: 0px;
}

#ticket-shelf.ytd-watch-flexy {
  display: none;
}

.ytp-live-badge.ytp-button {  
  width: auto;
}

ytd-reel-shelf-renderer {
  display: none;
}

#reply-button-end {
  margin-left: -16px;
}

#background.ytd-masthead {
  display: none;
}

#watch-page-skeleton {
  display: none;
}

ytd-secondary-search-container-renderer {
  display: none;
}

#vote-count-middle.ytd-comment-action-buttons-renderer {
  padding-right: 4px;
}

#notification-preference-button yt-button-shape > button.yt-spec-button-shape-next--tonal::after {
  border: none;
}

#notification-preference-button > ytd-subscription-notification-toggle-button-renderer-next > yt-button-shape > button > .yt-spec-button-shape-next--button-text-content {
  display: none;
}

#notification-preference-button > ytd-subscription-notification-toggle-button-renderer-next > yt-button-shape > button {
  padding: 0px;
  border-left: none;
}

#notification-preference-button > ytd-subscription-notification-toggle-button-renderer-next > yt-button-shape > button > .yt-spec-button-shape-next__icon {
  transform: none;
}

#notification-preference-button > ytd-subscription-notification-toggle-button-renderer-next > yt-button-shape > button::before {
  content: none;
}
```
