### ISSUE TITLE
add spacer for streams

### ISSUE THREAD

**Issue by TorutheRedFox** [omnidevZero/YouTubeRedux#42]
![image](https://user-images.githubusercontent.com/15708278/179356806-0fb618a3-ba7e-4ea6-b2db-e27fa270e826.png)

**Comment by TorutheRedFox** [comment]
quick fix for it
```CSS
ytd-menu-renderer ytd-menu-renderer .ytd-menu-renderer[style-target=button], .ytd-menu-renderer[style-target=button], ytd-button-renderer[is-icon-button][style-action-button]  {
    vertical-align: top;
}

ytd-video-primary-info-renderer:after {
    --yt-icon-button-icon-width: 24px;
    --yt-icon-button-icon-height: 24px;
    width: var(--yt-icon-width);
    height: var(--yt-icon-height);
    content: "";

    display: inline-block;
    box-sizing: border-box;
    font-size: 0;
}

yt-formatted-string.style-scope.ytd-toggle-button-renderer.style-text, yt-formatted-string.style-scope.ytd-toggle-button-renderer.style-default-active {
  font-weight: 500;
  font-size: 11px;
  text-decoration: none;
  white-space: nowrap;
  word-wrap: normal;
  line-height: normal;
  vertical-align: middle;
}

ytd-video-primary-info-renderer {
    padding: 16px 16px 0px 0px;
}

.redux-moved-info:last-of-type + yt-icon-button {
    transform: translateY(-2px);
}
```
